# 错误处理

## setTimeout 中的错误

你怎么看？.catch 会被触发么？解释你的答案。

``` javascript
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("Whoops!");
  }, 1000);
}).catch(alert);
```

### 解决方案

不会被触发，executor周围有隐式的try...catch，它会捕获同步错误，不会异步错误。